### ISSUE TITLE
node-expat issue

### ISSUE THREAD

**Issue by anandreddyks** [vchatterji/opml2json#2]
![image](https://cloud.githubusercontent.com/assets/6284338/11173103/d4653298-8c37-11e5-8e43-a928d179359f.png)

**Comment by Tapjay** [comment]
The module cannot be found as you need to run "npm i" in the directory to install all project dependencies. 

However, after doing this I still ran into issues (errors with package node-expat were thrown when npm i was ran) which I fixed by deleting the dependency in package.json and then running "npm i --save npm-expat".

**Comment by anandreddyks** [comment]
I tries installing node-expat ..
But I'm getting this issue

![image](https://cloud.githubusercontent.com/assets/6284338/11241605/18d7b702-8e22-11e5-83b3-b88a15b1d55c.png)

**Comment by Tapjay** [comment]
Did you open up package.json and delete the entry for node-expat under dependencies before running npm i again?

**Comment by Tapjay** [comment]
After doing that your dependencies section of the package.json file should look like this:

"dependencies": {
    "node-expat": "^2.3.11"
  }

I found this worked for me.

**Comment by vchatterji** [comment]
@JulianTapales thanks for the update. I have fixed the node-expat version in package.json
